# check the version of sparse convolution engine
env:
  spconv_ver: 2
data_root:
  # KITTI sequences root
  data_root_folder: "/lyh/KITTI_Velodyne"

extractor_config:
  seqs: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"]
  pretrained_backbone_model: "./models/backbone.ckpt"
  batch_num: 128

training_config:
  # KITTI sequences for training
  training_seqs: ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"]
  # training log folder
  log_folder: "./log"
  # pretrained model
  pretrained_vlad_model: "./models/vlad.ckpt"
  pos_threshold: 10
  neg_threshold: 50
  batch_size: 64
  epoch: 100000

test_config:
  # KITTI sequence 00 for evaluation
  seq: "10"
  # pretrained model
  test_overlap_model: "./models/overlap.ckpt"
  test_vlad_model: "./models/vlad.ckpt"
  th_min: 0
  th_max: 10
  th_max_pre: 10
  skip: 50
  batch_num: 48

